// Generated by pdfx init.
// See: https://pdfx.akashpise.dev/installation#theming
//
// Provides runtime theme overrides via React context.
// Wrap a subtree in <PdfxThemeProvider theme={myTheme}> to override defaults.

/* eslint-disable react-refresh/only-export-components */
// Intentional: this module exports both a component and hooks/context.
// Keeping a single import surface preserves the generated public API.

import {
  createContext,
  type DependencyList,
  type ReactNode,
  useContext,
} from "react";
import { theme as defaultTheme } from "./pdfx-theme";

type PdfxTheme = typeof defaultTheme;

export const PdfxThemeContext = createContext<PdfxTheme>(defaultTheme);

export interface PdfxThemeProviderProps {
  theme?: PdfxTheme;
  children: ReactNode;
}

export function PdfxThemeProvider({ theme, children }: PdfxThemeProviderProps) {
  const resolvedTheme = theme ?? defaultTheme;
  return (
    <PdfxThemeContext.Provider value={resolvedTheme}>
      {children}
    </PdfxThemeContext.Provider>
  );
}

export function usePdfxTheme(): PdfxTheme {
  return useContext(PdfxThemeContext);
}

/**
 * Calls factory() and returns the result.
 * The deps parameter is accepted for API compatibility with existing callers.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function useSafeMemo<T>(factory: () => T, _deps: DependencyList): T {
  return factory();
}
